/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atsvisualizer;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author filipeoliveira
 */
public class AtsMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form AtsMainFrame
     */
    
    ArrayList <atsMethod> methods;
    
    public AtsMainFrame() {
        methods = new ArrayList <atsMethod>();
        File fileWithMetrics = new File("metrics_to_gui.txt");
        try {
            read (fileWithMetrics);
        } catch (IOException ex) {
            Logger.getLogger(AtsMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }
    
    public void read(File file) throws IOException{
    Scanner scanner = new Scanner(file);
    while(scanner.hasNext()){
        String[] tokens = scanner.nextLine().split(";");
        if ( tokens.length >= 10 ){
            String method_description = tokens[0];
     double ats_CYCLO_PER_LOC = Double.parseDouble(tokens[1]);
     double ats_LOC_PER_OPERATION = Double.parseDouble(tokens[2]);
     double ats_NOM_PER_CLASS = Double.parseDouble(tokens[3]);
    double ats_NOC_PER_PACKAGE = Double.parseDouble(tokens[4]);
    double ats_CALLS_PER_OPERATION = Double.parseDouble(tokens[5]);
    double ats_FANOUT_PER_CALL = Double.parseDouble(tokens[6]);
    double ats_ANDC = Double.parseDouble(tokens[7]);
    double ats_AHH = Double.parseDouble(tokens[8]);
    String standardValues = tokens[9];
            atsMethod newM = new atsMethod ( method_description,  ats_CYCLO_PER_LOC, ats_LOC_PER_OPERATION, 
    ats_NOM_PER_CLASS, ats_NOC_PER_PACKAGE, ats_CALLS_PER_OPERATION,
    ats_FANOUT_PER_CALL, ats_ANDC, ats_AHH , standardValues );
            this.methods.add(newM);
            System.out.println("added new ats method: " + method_description );
           // this.listaMetricas.add(method_description);
       }
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaMetricas = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(listaMetricas, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(listaMetricas, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtsMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List listaMetricas;
    // End of variables declaration//GEN-END:variables
}
